### ISSUE TITLE
What is this problum?

### ISSUE THREAD

**Issue by FoxNT3** [ReVancedTeam/revanced-patches#10]
![화면 캡처 2022-05-05 172217](https://user-images.githubusercontent.com/104974848/166886588-ff958315-c86f-43eb-8732-ebb0f3299409.png)
What is this Ploblum????
I was following https://github.com/ReVancedTeam/revanced-documentation (Building the ReVanced patches)

**Comment by Canny1913** [comment]
open "\revanced-patches\src\main\kotlin\app\revanced\patches\youtube\misc\FixLocaleConfigErrorPatch.kt" using notepad

add this to the beginning of the file

@file:Suppress("JAVA_MODULE_DOES_NOT_EXPORT_PACKAGE")

**Comment by FoxNT3** [comment]
Thank You~
but What is this problum??
![화면 캡처 2022-05-05 174522](https://user-images.githubusercontent.com/104974848/166890166-ab9c0fa6-ffad-4e68-971d-ee24d2339f33.png)
I was following https://github.com/ReVancedTeam/revanced-documentation/wiki/Building-the-ReVanced-cli
(Building the ReVanced cli)

**Comment by Canny1913** [comment]
> Thank You~ but What is this problum?? ![화면 캡처 2022-05-05 174522](https://user-images.githubusercontent.com/104974848/166890166-ab9c0fa6-ffad-4e68-971d-ee24d2339f33.png) I was following https://github.com/ReVancedTeam/revanced-documentation/wiki/Building-the-ReVanced-cli (Building the ReVanced cli)

im trying to fix that right now
same thing happened to me

**Comment by oSumAtrIX** [comment]
The FileSystem error is due to wrong jdk version, use java 1.8, and the package one is a current issue, please wait for a fix. Check #9 for reference.

**Comment by oSumAtrIX** [comment]
Closing with #11
